// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625102333_AddWorkflowFieldsToJuridique")]
    partial class AddWorkflowFieldsToJuridique
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("NumeroBureauOrdre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceActuel")
                        .HasColumnType("int");

                    b.Property<int>("StatutActuel")
                        .HasColumnType("int");

                    b.Property<string>("Sujet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Documents");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Document");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WebApplication1.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgentDestinataireId")
                        .HasColumnType("int");

                    b.Property<int>("CourrierAdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTransaction")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("NomPersonneExterne")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarques")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ServiceDestinataireId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceDestination")
                        .HasColumnType("int");

                    b.Property<int>("ServiceOrigine")
                        .HasColumnType("int");

                    b.Property<string>("StatutEtape")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UtilisateurId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("WebApplication1.Models.CourrierAdministratif", b =>
                {
                    b.HasBaseType("WebApplication1.Models.Document");

                    b.Property<DateTime>("DateReception")
                        .HasColumnType("datetime2");

                    b.Property<string>("Expediteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroOrdre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCircuit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CourrierAdministratif");
                });

            modelBuilder.Entity("WebApplication1.Models.DossierJuridique", b =>
                {
                    b.HasBaseType("WebApplication1.Models.Document");

                    b.Property<string>("AutoriteRetrait")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Circuit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("datetime2");

                    b.Property<string>("Demandeur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EtapeJalsatActuelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EtapeService")
                        .HasColumnType("int");

                    b.Property<string>("EtatGlobal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JalsatTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotifException")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroDossierJuridique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaslimTransaction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeCircuit")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Documents", t =>
                        {
                            t.Property("TypeCircuit")
                                .HasColumnName("DossierJuridique_TypeCircuit");
                        });

                    b.HasDiscriminator().HasValue("DossierJuridique");
                });

            modelBuilder.Entity("WebApplication1.Models.Transaction", b =>
                {
                    b.HasOne("WebApplication1.Models.Document", "Document")
                        .WithMany("Transactions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("WebApplication1.Models.Document", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
